### ISSUE TITLE
入退出をgithubの草⸮みたいにする

### ISSUE THREAD

**Issue by npJxx** [juggler-boryo/aigrid#2]
<img width="404" alt="Screenshot 0006-11-30 at 0 52 46" src="https://github.com/user-attachments/assets/95373e7b-e258-4c1a-b2a8-042a1c034fe7">

**Comment by jumang4423** [comment]
protectedRouter.HandleFunc("/inout/{uid}/kusa", handlers.GetInoutHistoryByMonthHandler).Methods("GET")

returns

{ count: number; date: Date }[]
