### ISSUE TITLE
基金システム

### ISSUE THREAD

**Issue by Andyyyy64** [juggler-boryo/aigrid#5]
買いたいものを挙げて、募金を募る
自分これくらい払います！みたいなもの

例：
jumango: ジャグラーに冷蔵庫ほしいです。皆さんでかいませんか？ -> aigridで値段とbetの締め切り日を明記

andy: 2000円払います！ -> aigridでbet

npjxx: 1000円払います！ -> aigridでbet

、、、

など

paypayありだよね～

**Comment by jumang4423** [comment]
tamaki protocolのkind=0を基金システムにしようと考えている。現時点で思いつく例：

- ２週間テザリング利用権
- 冷蔵庫基金調達
- なっとうづくりイベント
- ぬかづけイベント

必要なフィールドは
- participants_uids
- title
- memo
- price (-1 未定、0~円)
